version: "3.9"

services:
  app:
    build: .
    container_name: fitness-tracker-app

    ports:
      - "3000:3000"

    env_file:
      - .env

    depends_on:
      - mysql

    restart: unless-stopped

  mysql:
    image: mysql:8.4

    container_name: fitness-tracker-db

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data: